version: '2'

services:

  snowboy:
    build: .
    image: wn1980/build-snowboy${TAG}
    container_name: snowboy
    command: tail -f /dev/null
    privileged: true
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - "/dev/snd:/dev/snd"
      - "./asoundrc.txt:/root/.asoundrc:rw"
      - "./workspace:/workspace:rw"